In [1]:
import pandas as pd
import numpy as np

## Daily weather

In [2]:
df_weather = pd.read_csv('../../data/intermediate/weather_daily.csv')
df_weather

,date,county,voivodeship,seat,temperature,precipation,humidity
0,2015-01-01,żywiecki,śląskie,Żywiec,-1.910424,0.121253,89.021673
1,2015-01-01,płoński,mazowieckie,Płońsk,1.534776,0.250138,93.733571
2,2015-01-01,płocki,mazowieckie,Płock,1.760262,0.321921,93.564604
3,2015-01-01,pyrzycki,zachodniopomorskie,Pyrzyce,3.045660,0.340035,89.239130
4,2015-01-01,pułtuski,mazowieckie,Pułtusk,1.270091,0.069441,94.024695
...,...,...,...,...,...,...,...
1249055,2023-12-31,grójecki,mazowieckie,Grójec,2.029301,0.000000,94.708750
1249056,2023-12-31,gryfiński,zachodniopomorskie,Gryfino,4.608542,0.000000,90.230486
1249057,2023-12-31,gryficki,zachodniopomorskie,Gryfice,4.179861,5.300000,88.555556
1249058,2023-12-31,iławski,warmińsko-mazurskie,Iława,1.631944,0.000000,96.506944
1249059,2023-12-31,żywiecki,śląskie,Żywiec,4.792361,0.200000,81.881944

In [3]:
# Handle temperature outliers
temp_outliers = df_weather.temperature.nlargest(2).index
df_weather.loc[temp_outliers, 'temperature'] = np.nan

# Handle humidity outliers by clipping to 100
df_weather['humidity'] = df_weather['humidity'].clip(upper=100)

# Handle precipitation outliers
precip_outliers = df_weather.precipation.nlargest(50).index
df_weather.loc[precip_outliers, 'precipation'] = np.nan

# Convert precipitation values less than 0.01 to zero
df_weather.loc[df_weather.precipation < 0.01, 'precipation'] = 0

In [4]:
print(df_weather.describe())

        temperature   precipation      humidity
count  1.248348e+06  1.248774e+06  1.248505e+06
mean   9.594676e+00  1.768193e+00  7.741987e+01
std    7.896140e+00  4.730923e+00  1.192376e+01
min   -2.203600e+01  0.000000e+00  4.397253e+00
25%    3.374675e+00  0.000000e+00  6.929637e+01
50%    9.357548e+00  1.578103e-01  7.874636e+01
75%    1.624246e+01  1.660525e+00  8.698600e+01
max    3.597940e+01  2.454732e+02  1.000000e+02

In [5]:
df_weather.to_csv('../../data/processed/weather_daily.csv', index=False)

## Incidents weather

In [6]:
df_incidents = pd.read_csv('../../data/intermediate/incidents.csv')
df_incidents

/var/folders/yp/gjwvp9611c96kbtrz5ssff_h0000gn/T/ipykernel_53782/2217494344.py:1: DtypeWarning: Columns (9,10,11,13,14,15,16,17,18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df_incidents = pd.read_csv('../../data/intermediate/incidents.csv')

,id,datetime,longitude,latitude,voivodeship,county,municipality,city,incident_type,other_cause,...,vehicle_types_trucks,vehicle_types_semi-trailer_tractors,road_accidents_total_accidents,road_accidents_total_casualties,road_accidents_fatalities,road_accidents_injured,road_types_municipal_and_county_paved_roads_per_100km2,road_types_municipal_and_county_paved_roads_per_10.000_inhabitants,precipation,precipation_24h
0,108526474,2020-01-01 00:15:00,16.761389,52.514028,wielkopolskie,poznański,Rokietnica,Rokietnica,Najechanie na pieszego,Brak,...,43349.0,10671.0,365.0,NaN,21.0,464.0,97.2,42.9,0.0,0.0
1,108526534,2020-01-01 00:20:00,18.953917,51.895527,łódzkie,poddębicki,Poddębice,Poddębice,Najechanie na pieszego,Brak,...,5163.0,262.0,42.0,NaN,2.0,59.0,73.0,160.7,0.0,0.0
2,108523125,2020-01-01 00:25:00,14.568027,53.435666,zachodniopomorskie,Szczecin,Szczecin,Szczecin,Zderzenie pojazdów boczne,Brak,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3,108523133,2020-01-01 00:55:00,20.929499,53.849416,warmińsko-mazurskie,olsztyński,Biskupiec,Rzeck,Najechanie na drzewo,Brak,...,10951.0,669.0,135.0,NaN,8.0,172.0,38.2,84.3,0.0,0.0
4,108526549,2020-01-01 01:20:00,23.047500,53.405555,podlaskie,moniecki,Jasionówka,Brak w danych źródłowych,Wywrócenie się pojazdu,Brak,...,2807.0,234.0,22.0,NaN,1.0,26.0,40.1,143.3,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88602,125862934,2023-12-31 21:39:00,16.966860,50.850805,dolnośląskie,strzeliński,Borów,Głownin,Najechanie na drzewo,NaN,...,4419.0,421.0,23.0,27.0,4.0,23.0,79.1,117.7,0.0,0.0
88603,125860432,2023-12-31 22:20:00,19.934027,50.074999,małopolskie,Kraków,Kraków,Kraków,Najechanie na pojazd unieruchomiony,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
88604,125862027,2023-12-31 23:16:00,20.519268,52.259491,mazowieckie,warszawski zachodni,Kampinos,Wiejca,Najechanie na drzewo,NaN,...,25941.0,5565.0,48.0,59.0,9.0,50.0,128.8,50.8,0.0,0.0
88605,125860445,2023-12-31 23:26:00,17.918390,50.673988,opolskie,Opole,Opole,Opole,Zderzenie pojazdów boczne,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
88606,125862954,2023-12-31 23:48:00,19.104167,50.812222,śląskie,Częstochowa,Częstochowa,Częstochowa,Najechanie na pieszego,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [7]:
df_incidents.describe()

,id,longitude,latitude,speed_limit,elevation,temperature,humidity,indicators_population_per_1_km2,road_types_paved_surface,road_types_improved_paved_surface,...,vehicle_types_trucks,vehicle_types_semi-trailer_tractors,road_accidents_total_accidents,road_accidents_total_casualties,road_accidents_fatalities,road_accidents_injured,road_types_municipal_and_county_paved_roads_per_100km2,road_types_municipal_and_county_paved_roads_per_10.000_inhabitants,precipation,precipation_24h
count,8.860700e+04,88607.000000,88607.000000,67676.000000,88607.000000,8.860600e+04,88607.000000,58090.000000,58090.000000,58090.000000,...,58090.000000,58090.000000,58090.000000,13517.000000,58090.000000,58090.000000,58090.000000,58090.000000,88435.000000,88455.000000
mean,1.164672e+08,19.205126,51.739501,59.760979,171.831866,5.266003e+13,71.506299,117.928127,561.525268,489.192611,...,10820.825116,1755.997211,75.664813,94.981209,7.976347,90.473903,97.155884,99.250554,0.094475,1.746068
std,6.909173e+06,2.047744,1.356208,20.789065,106.601385,1.789497e+16,19.177624,85.328766,368.372039,320.733745,...,7457.134994,2883.282761,60.965596,82.701073,5.314910,76.390149,41.706042,40.758351,0.596406,4.625238
min,1.085231e+08,14.127694,49.005555,0.000000,-1.432025,-1.411557e+18,9.639741,18.100000,38.700000,36.900000,...,1526.000000,48.000000,3.000000,3.000000,0.000000,3.000000,21.700000,33.200000,0.000000,0.000000
25%,1.096552e+08,17.776471,50.596319,50.000000,101.635310,5.382559e+00,56.663155,63.600000,318.400000,267.300000,...,6091.750000,655.000000,36.000000,42.000000,4.000000,39.000000,69.100000,69.300000,0.000000,0.000000
50%,1.135338e+08,19.357639,51.732999,50.000000,155.922970,1.306772e+01,75.533721,94.200000,480.200000,418.100000,...,8822.000000,1076.000000,55.000000,68.000000,7.000000,65.000000,93.100000,91.600000,0.000000,0.000000
75%,1.242866e+08,20.788486,52.551556,70.000000,222.399300,1.932218e+01,88.210383,143.700000,709.500000,612.900000,...,13943.000000,1688.000000,94.000000,111.000000,10.000000,116.000000,114.300000,123.600000,0.000000,1.200000
max,1.259238e+08,24.129694,54.833583,140.000000,1307.587800,4.139407e+18,100.000000,729.300000,2281.700000,1925.900000,...,47387.000000,43857.000000,365.000000,421.000000,32.000000,464.000000,292.300000,352.200000,34.000000,131.300000

In [8]:
# Find extreme temperature values
highest_temps = df_incidents.temperature.nlargest(49)
lowest_temps = df_incidents.temperature.nsmallest(42)

# Combine highest and lowest temps into one Series of outliers
temp_outliers = pd.concat([highest_temps, lowest_temps])

# Set these extreme values to NaN
df_incidents.loc[temp_outliers.index, 'temperature'] = np.nan

In [14]:
print(df_incidents[['temperature', 'humidity', 'precipation', 'precipation_24h']].describe())

        temperature      humidity   precipation  precipation_24h
count  88515.000000  88607.000000  88435.000000     88455.000000
mean      12.551166     71.506299      0.094475         1.746068
std        8.628702     19.177624      0.596406         4.625238
min      -19.868876      9.639741      0.000000         0.000000
25%        5.389672     56.663155      0.000000         0.000000
50%       13.065802     75.533721      0.000000         0.000000
75%       19.315676     88.210383      0.000000         1.200000
max       35.976148    100.000000     34.000000       131.300000

In [15]:
df_incidents.to_csv('../../data/processed/incidents.csv', index=False)